In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame({
    'Date':['2026--05-01','2026--05-01','2026--05-02','2026--05-02','2026--05-03','2026--05-03','2026--05-03'],
    'Item':['Maggi','Biscuit','Maggi','Chips','Biscuit','Chips','Maggi'],
    'Qty_sold':[10,20,15,25,30,10,12],
    'Cost_price':[10,5,10,8,5,8,10],
    'Selling_Price':[12,7,12,10,7,10,12]
})
df['Date']=pd.to_datetime(df['Date'])

In [4]:
df

        Date     Item  Qty_sold  Cost_price  Selling_Price
0 2026-05-01    Maggi        10          10             12
1 2026-05-01  Biscuit        20           5              7
2 2026-05-02    Maggi        15          10             12
3 2026-05-02    Chips        25           8             10
4 2026-05-03  Biscuit        30           5              7
5 2026-05-03    Chips        10           8             10
6 2026-05-03    Maggi        12          10             12

In [6]:
df=df.assign(Total_cost=df['Qty_sold']*df['Cost_price'])
df

        Date     Item  Qty_sold  Cost_price  Selling_Price  Total_cost
0 2026-05-01    Maggi        10          10             12         100
1 2026-05-01  Biscuit        20           5              7         100
2 2026-05-02    Maggi        15          10             12         150
3 2026-05-02    Chips        25           8             10         200
4 2026-05-03  Biscuit        30           5              7         150
5 2026-05-03    Chips        10           8             10          80
6 2026-05-03    Maggi        12          10             12         120

In [8]:
df=df.assign(Total_revenue=df['Qty_sold']*df['Selling_Price'])
df

,Date,Item,Qty_sold,Cost_price,Selling_Price,Total_cost,Total_revenue
0,2026-05-01,Maggi,10,10,12,100,120
1,2026-05-01,Biscuit,20,5,7,100,140
2,2026-05-02,Maggi,15,10,12,150,180
3,2026-05-02,Chips,25,8,10,200,250
4,2026-05-03,Biscuit,30,5,7,150,210
5,2026-05-03,Chips,10,8,10,80,100
6,2026-05-03,Maggi,12,10,12,120,144

In [9]:
df=df.assign(Profit=df['Total_revenue']-df['Total_cost'])
df

,Date,Item,Qty_sold,Cost_price,Selling_Price,Total_cost,Total_revenue,Profit
0,2026-05-01,Maggi,10,10,12,100,120,20
1,2026-05-01,Biscuit,20,5,7,100,140,40
2,2026-05-02,Maggi,15,10,12,150,180,30
3,2026-05-02,Chips,25,8,10,200,250,50
4,2026-05-03,Biscuit,30,5,7,150,210,60
5,2026-05-03,Chips,10,8,10,80,100,20
6,2026-05-03,Maggi,12,10,12,120,144,24

In [13]:
df2=df.groupby('Date')['Profit'].sum()
df2

Date
2026-05-01     60
2026-05-02     80
2026-05-03    104
Name: Profit, dtype: int64

In [31]:
print("Best_day",df2.idxmax(),"with",df2.max(),"Rs.")

Best_day 2026-05-03 00:00:00 with 104 Rs.

In [32]:
df3=df.groupby('Item')['Qty_sold'].sum()
print("Best selling item-",df3.idxmax(),"-",df3.max(),"Unit")

Best selling item- Biscuit - 50 Unit

In [35]:
df4=df.groupby('Item')['Profit'].sum()
print("Most profitable item:",df4.idxmax(),"-",df4.max(),"Rs total profit")

Most profitable item: Biscuit - 100 Rs total profit

In [51]:
df['Profit_margin']=(df['Profit']/df['Total_revenue'])*100 
df

,Date,Item,Qty_sold,Cost_price,Selling_Price,Total_cost,Total_revenue,Profit,Profit_margin
0,2026-05-01,Maggi,10,10,12,100,120,20,16.666667
1,2026-05-01,Biscuit,20,5,7,100,140,40,28.571429
2,2026-05-02,Maggi,15,10,12,150,180,30,16.666667
3,2026-05-02,Chips,25,8,10,200,250,50,20.000000
4,2026-05-03,Biscuit,30,5,7,150,210,60,28.571429
5,2026-05-03,Chips,10,8,10,80,100,20,20.000000
6,2026-05-03,Maggi,12,10,12,120,144,24,16.666667

In [52]:
df.to_csv("Kirana_sales_Report.csv",index=False)