In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({
    'Name':['Rohit','Aman','Priya','Sneha','Vikas'],
    'Maths':[78,92,85,60,74],
    'Science':[88,81,90,55,79],
    'English':[75,89,95,62,80]
})

In [3]:
df

    Name  Maths  Science  English
0  Rohit     78       88       75
1   Aman     92       81       89
2  Priya     85       90       95
3  Sneha     60       55       62
4  Vikas     74       79       80

In [4]:
df2=df.copy()

In [7]:
df=df.assign(Total_Marks=df["Maths"]+df["Science"]+df["English"])

In [8]:
df

    Name  Maths  Science  English  Total_Marks
0  Rohit     78       88       75          241
1   Aman     92       81       89          262
2  Priya     85       90       95          270
3  Sneha     60       55       62          177
4  Vikas     74       79       80          233

In [14]:
Max_marks_idx=df["Total_Marks"].idxmax()

In [24]:
print(df.loc[Max_marks_idx])

Name           Priya
Maths             85
Science           90
English           95
Total_Marks      270
Name: 2, dtype: object

In [25]:
df["Result"]=df["Total_Marks"].apply(lambda x:"Pass" if x>=240 else "Fail")

In [26]:
df

    Name  Maths  Science  English  Total_Marks Result
0  Rohit     78       88       75          241   Pass
1   Aman     92       81       89          262   Pass
2  Priya     85       90       95          270   Pass
3  Sneha     60       55       62          177   Fail
4  Vikas     74       79       80          233   Fail